//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebService.practica {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="practica.PracticaSoap")]
    public interface PracticaSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento DiaSemanaResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DiaSemana", ReplyAction="*")]
        WebService.practica.DiaSemanaResponse DiaSemana(WebService.practica.DiaSemanaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DiaSemana", ReplyAction="*")]
        System.Threading.Tasks.Task<WebService.practica.DiaSemanaResponse> DiaSemanaAsync(WebService.practica.DiaSemanaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento mesResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mes", ReplyAction="*")]
        WebService.practica.mesResponse mes(WebService.practica.mesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mes", ReplyAction="*")]
        System.Threading.Tasks.Task<WebService.practica.mesResponse> mesAsync(WebService.practica.mesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DiaSemanaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DiaSemana", Namespace="http://tempuri.org/", Order=0)]
        public WebService.practica.DiaSemanaRequestBody Body;
        
        public DiaSemanaRequest() {
        }
        
        public DiaSemanaRequest(WebService.practica.DiaSemanaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DiaSemanaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int n;
        
        public DiaSemanaRequestBody() {
        }
        
        public DiaSemanaRequestBody(int n) {
            this.n = n;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DiaSemanaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DiaSemanaResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebService.practica.DiaSemanaResponseBody Body;
        
        public DiaSemanaResponse() {
        }
        
        public DiaSemanaResponse(WebService.practica.DiaSemanaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DiaSemanaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DiaSemanaResult;
        
        public DiaSemanaResponseBody() {
        }
        
        public DiaSemanaResponseBody(string DiaSemanaResult) {
            this.DiaSemanaResult = DiaSemanaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class mesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="mes", Namespace="http://tempuri.org/", Order=0)]
        public WebService.practica.mesRequestBody Body;
        
        public mesRequest() {
        }
        
        public mesRequest(WebService.practica.mesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class mesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int meses;
        
        public mesRequestBody() {
        }
        
        public mesRequestBody(int meses) {
            this.meses = meses;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class mesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="mesResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebService.practica.mesResponseBody Body;
        
        public mesResponse() {
        }
        
        public mesResponse(WebService.practica.mesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class mesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string mesResult;
        
        public mesResponseBody() {
        }
        
        public mesResponseBody(string mesResult) {
            this.mesResult = mesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PracticaSoapChannel : WebService.practica.PracticaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PracticaSoapClient : System.ServiceModel.ClientBase<WebService.practica.PracticaSoap>, WebService.practica.PracticaSoap {
        
        public PracticaSoapClient() {
        }
        
        public PracticaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PracticaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PracticaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PracticaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService.practica.DiaSemanaResponse WebService.practica.PracticaSoap.DiaSemana(WebService.practica.DiaSemanaRequest request) {
            return base.Channel.DiaSemana(request);
        }
        
        public string DiaSemana(int n) {
            WebService.practica.DiaSemanaRequest inValue = new WebService.practica.DiaSemanaRequest();
            inValue.Body = new WebService.practica.DiaSemanaRequestBody();
            inValue.Body.n = n;
            WebService.practica.DiaSemanaResponse retVal = ((WebService.practica.PracticaSoap)(this)).DiaSemana(inValue);
            return retVal.Body.DiaSemanaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebService.practica.DiaSemanaResponse> WebService.practica.PracticaSoap.DiaSemanaAsync(WebService.practica.DiaSemanaRequest request) {
            return base.Channel.DiaSemanaAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebService.practica.DiaSemanaResponse> DiaSemanaAsync(int n) {
            WebService.practica.DiaSemanaRequest inValue = new WebService.practica.DiaSemanaRequest();
            inValue.Body = new WebService.practica.DiaSemanaRequestBody();
            inValue.Body.n = n;
            return ((WebService.practica.PracticaSoap)(this)).DiaSemanaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebService.practica.mesResponse WebService.practica.PracticaSoap.mes(WebService.practica.mesRequest request) {
            return base.Channel.mes(request);
        }
        
        public string mes(int meses) {
            WebService.practica.mesRequest inValue = new WebService.practica.mesRequest();
            inValue.Body = new WebService.practica.mesRequestBody();
            inValue.Body.meses = meses;
            WebService.practica.mesResponse retVal = ((WebService.practica.PracticaSoap)(this)).mes(inValue);
            return retVal.Body.mesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebService.practica.mesResponse> WebService.practica.PracticaSoap.mesAsync(WebService.practica.mesRequest request) {
            return base.Channel.mesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebService.practica.mesResponse> mesAsync(int meses) {
            WebService.practica.mesRequest inValue = new WebService.practica.mesRequest();
            inValue.Body = new WebService.practica.mesRequestBody();
            inValue.Body.meses = meses;
            return ((WebService.practica.PracticaSoap)(this)).mesAsync(inValue);
        }
    }
}
